# Test episodes API and/or Client

@bearer = ey...
@episodes_url=
#@episodes_url=http://localhost:3100/api/episodes

# Episodes getAll
GET {{episodes_url}} HTTP/1.1
User-agent: ex-10-client
Authorization: Bearer {{bearer}}

### Swagger
GET http://localhost:3100/doc HTTP/1.1
