## Defining variables
@tenant_id=<insert>
@client_id=<insert>
@scope=user.read openid profile offline_access

### 1. Device authorization request
POST https://login.microsoftonline.com/{{tenant_id}}/oauth2/v2.0/devicecode
Content-Type: application/x-www-form-urlencoded

client_id={{client_id}}
&scope={{scope}}



### Go to the verification_uri: https://microsoft.com/devicelogin and insert received USER_CODE
###
### Insert received DEVICE_CODE from first request into next request to poll for token
###
@device_code=<insert received device_code>

### 2. Authenticating the user
POST https://login.microsoftonline.com/{tenant}/oauth2/v2.0/token
Content-Type: application/x-www-form-urlencoded

grant_type=urn:ietf:params:oauth:grant-type:device_code
&client_id={{client_id}}
&device_code={{device_code}}
